# STAT107_FinalProject_Team10
## Angelina How, Sara Munkhbayar, Bethany Galias

### Data Files:
- Harry Potter All Books.txt: text file that has the entire text of all 7 Harry Potter books.
- Percy Jackson 1.txt: text file that has all of the text in the book Percy Jackson and the Lightning Thief.
- Percy Jackson 2.txt: text file that has all of the text in the book Percy Jackson and the Sea of Monsters.
- Percy Jackson 3.txt: text file that has all of the text in the book Percy Jackson and the Titan's Curse.
- Percy Jackson 4.txt: text file that has all of the text in the book Percy Jackson and the Battle of the Labyrinth.
- Percy Jackson 5.txt: text file that has all of the text in the book Percy Jackson and the Last Olympian.

### Function Files:
- 11_requirements: R source code file that includes the necessary packages for the data cleaning, data processing, and analysis.

### Analysis Files:
- 11_DataCleaning: Rmd file for cleaning the data (removing punctuation, numbers, special characters, and converting letters to lowercase) and saving it to the file 12_DataSaving.
- 12_DataSaving: R data file of the cleaned data.
- 21_DataProcessing: Rmd file for processing the data for analysis. 
- 31_DataVisualization: Rmd file for making simple visualizations of the word frequencies for each book series
- WordFreqHistograms.png: the data visualizations for the word frequencies for each book series 

### Report File:
- FinalReport.Rmd: Our project report that describes our question, methodology, and conclusions that we aim to reach. 

### Instructions: Please run the files in this order:
1. Run 11_DataCleaning.Rmd.
2. Run 21_DataProcessing.Rmd.
3. Run 31_DataVisualization.Rmd.
4. Run 41_TextClassifier.Rmd.
5. Run FinalReport.Rmd.